---
abstract: 'read a Google AdSense performance report'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Adsense
no_index:
  directory:
    - t
    - inc
requires:
  Date::Calc: 0
  DateTime: 0
resources:
  bugtracker: https://github.com/benkasminbullock/Data-Adsense/issues
  repository: https://github.com/benkasminbullock/Data-Adsense
version: 0.01
